In [1]:
pip --version

pip 23.2.1 from C:\Users\Admin\anaconda3\Lib\site-packages\pip (python 3.11)

Note: you may need to restart the kernel to use updated packages.


In [2]:
print("Welcome nithu")

Welcome nithu


In [3]:
pip install camelcase

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for camelcase: filename=camelcase-0.2-py3-none-any.whl size=1779 sha256=83bb27bd627afda7322122897eca1830540a751807a1153f9490ad70b02d2667
  Stored in directory: c:\users\admin\appdata\local\pip\cache\wheels\9b\03\38\e96c3419390e51c6f282e9793e392eb2996b4059eb6739165b
Successfully built camelcase
Note: you may need to restart the kernel to use updated packages.


In [4]:
import camelcase
c=camelcase.CamelCase()
text="hello"
print(c.hump(text))

Hello


In [5]:
pip list

Package                       Version
----------------------------- ---------------
aiobotocore                   2.5.0
aiofiles                      22.1.0
aiohttp                       3.8.5
aioitertools                  0.7.1
aiosignal                     1.2.0
aiosqlite                     0.18.0
alabaster                     0.7.12
anaconda-anon-usage           0.4.2
anaconda-catalogs             0.2.0
anaconda-client               1.12.1
anaconda-cloud-auth           0.1.3
anaconda-navigator            2.5.0
anaconda-project              0.11.1
anyio                         3.5.0
appdirs                       1.4.4
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
astroid                       2.14.2
astropy                       5.1
asttokens                     2.0.5
async-timeout                 4.0.2
atomicwrites                  1.4.0
attrs                         22.1.0
Automat                       20.2.0
autopep8

In [6]:
import numpy
arr=numpy.array([2,8,10,5,9])
print(arr)

[ 2  8 10  5  9]


In [7]:
import numpy as np
arr=np.array([2,8,10,5,9])
print(type(arr))

<class 'numpy.ndarray'>


In [8]:
import numpy as np
arr=np.array(5)
arr1=np.array([2,8,10,5,9])
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


In [10]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
print(arr[0])
# print(arr[5])
print(arr[-1])

[1 2 3 4 5]
1
5


In [14]:
import numpy as np
arr=np.array([1,2,3,4,5])
for i in arr:
    print(i)

1
2
3
4
5


In [15]:
import numpy as np
arr=np.array([1,2,3,4,5])
for i in range(len(arr)):
    print(arr[i])

1
2
3
4
5


In [26]:
# To create a array and get user input then find the SUM and AVERAGE
import numpy as np
arr=np.array([1,2,3,4,5])
sum=0
for i in arr:
    sum+=i
print(sum)
print(sum/(len(arr)))
# print(arr[::-1])
length=(len(arr))*-1
for i in range(-1,length-1,-1):
    print(arr[i])

15
3.0
5
4
3
2
1


In [19]:
#get user input
arr=[]
n=int(input())
for i in range(n):
    ele=int(input())
    arr.append(ele)
print(type(arr))

3
12
13
14
<class 'list'>


In [2]:
#find max value in array
#find second max value in array
arr=[]
firstmax=0
n=int(input())
for i in range(n):
    ele=int(input())
    arr.append(ele)
for i in arr:
    if(i>firstmax):
        firstmax=i
print("firstmax:",firstmax)
secmax=0
for i in arr:
    if(i>secmax and i!=firstmax):
        secmax=i
print("secondmax:",secmax)
    

5
22
33
44
66
78
firstmax: 78
secondmax: 66


In [33]:
#creating a new 2d array
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("First 1D array:",a[0])
print("Second 1D array:",a[1])
print("Third 1D array:",a[2])

First 1D array: [1 2 3]
Second 1D array: [4 5 6]
Third 1D array: [7 8 9]


In [34]:
# printing row wise elements in 2D array
print("Accessing row 0 elements:")
print(a[0,0])
print(a[0,1])
print(a[0,2])
print("Accessing row 1 elements:")
print(a[1,0])
print(a[1,1])
print(a[1,2])
print("Accessing row 2 elements:")
print(a[2,0])
print(a[2,1])
print(a[2,2])

Accessing row 0 elements:
1
2
3
Accessing row 1 elements:
4
5
6
Accessing row 2 elements:
7
8
9


In [35]:
#accessing column wise elements in 2D array
print("Accessing row 0 elements:")
print(a[0,0])
print(a[1,0])
print(a[2,0])
print("Accessing row 1 elements:")
print(a[0,1])
print(a[1,1])
print(a[2,1])
print("Accessing row 2 elements:")
print(a[0,2])
print(a[1,2])
print(a[2,2])

Accessing row 0 elements:
1
4
7
Accessing row 1 elements:
2
5
8
Accessing row 2 elements:
3
6
9


In [36]:
#printing 2D array using for loop
print("The given matrix is:")
for i in range(len(a)):
    for j in range(len(a[i])):
        print(a[i,j],end=' ')
    print()

The given matrix is:
1 2 3 
4 5 6 
7 8 9 


In [37]:
for i in a:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [38]:
#printing 3d array
a=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
for i in a:
    for j in i:
        for k in j:
            print(k,end=' ')
        print()

1 2 3 
4 5 6 
7 8 9 
10 11 12 
13 14 15 
16 17 18 


Array slicing

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

In [39]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a[0:5])

[1 2 3 4 5]


In [40]:
print(a[0:])
print(a[:])
print(a[-10:-5])
print(a[0::2])

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5]
[1 3 5 7 9]


In [41]:
#Slicing 2D Arrays
import numpy as np
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a)
print(a[1,1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[7 8 9]


Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer b - boolean u - unsigned integer f - float c - complex float m - timedelta M - datetime O - object S - string U - unicode string V - fixed chunk of memory for other type ( void )
#Checking datatype of an array-dtype property

In [42]:
a=np.array([1,2,3])
b=np.array([2.2,4.5,8.9])
c=np.array(['Tushar','Saran','c'])
print(a.dtype)
print(b.dtype)
print(c.dtype)

int32
float64
<U6


In [43]:
#Creating arrays with defined datatype
import numpy as np
a=np.array([1,2,3],dtype='S')
print(a)
print(a.dtype)

[b'1' b'2' b'3']
|S1


In [44]:
a=np.array([1,'c',3],dtype='i')

ValueError: invalid literal for int() with base 10: 'c'

In [45]:
#Converting datatypes-astype() method
import numpy as np
a=np.array([1.1,2.2,3.3])
b=a.astype('i')
print(a)
print(a.dtype)
print(b)
print(b.dtype)
a=np.array([1,-2,0])
b=a.astype(bool)
print(a)
print(a.dtype)
print(b)
print(b.dtype)

[1.1 2.2 3.3]
float64
[1 2 3]
int32
[ 1 -2  0]
int32
[ True  True False]
bool


Array copy and view

Copy: * Creates a new array * Any changes made to copy will not reflect on original and vice versa View: * Just a view of the original array * Changes made in view will reflect on original

In [47]:
#copy method
import numpy as np
a=np.array([1,-2,0])
b=a.copy()
a[0]=10
print("Array a:",a)
print("Array b:",b)

Array a: [10 -2  0]
Array b: [ 1 -2  0]


In [48]:
#view method
import numpy as np
a=np.array([1,-2,0])
b=a.view()
a[0]=10
print("Array a:",a)
print("Array b:",b)

Array a: [10 -2  0]
Array b: [10 -2  0]


In [49]:
#Check if array owns its data-base attribute
a=np.array([1,-2,0])
b=a.copy()
c=a.view()
print(b.base)
print(c.base)
print(a.base)

None
[ 1 -2  0]
None


In [50]:
#Array shape
import numpy as np
a=np.array([1,-2,0])
print(a.shape)
a=np.array([[1,-2,0],[4,5,6]])
print(a.shape)

(3,)
(2, 3)


In [56]:
#Reshaping arrays-changing dimension of the array
a=np.array([1,2,3,4,5,6,7,8,9,10])
b=a.reshape(5,2)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [52]:
b=a.reshape(2,2,2)
#Unknown dimension
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3,-1)
print(a)
print(b)

ValueError: cannot reshape array of size 9 into shape (2,2,2)

In [57]:
#Iteration using nditer()
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in np.nditer(a):
    print(x)

1
2
3
4
5
6
7
8
9


In [58]:
#converting integer to string
a=np.array([1,2,3,4,5])
for x in np.nditer(a,flags=['buffered'],op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'
b'4'
b'5'


In [59]:
a=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(a[:,::2]):
    print(x)

1
3
5
7


In [60]:
#Enumerated iteration using ndenumerate()
import numpy as np
a=np.array([1,2,3,4])
b=np.array([[1,2,3,4],[5,6,7,8]])
for i,x in np.ndenumerate(a):
    print(i,x)
for i,x in np.ndenumerate(b):
    print(i,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [61]:
#concatenate method for two arrays
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6 7 8]


In [62]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a,b))
print("First array\n",a)
print("Second array\n",b)
print("Result array\n",c)

First array
 [[1 2]
 [3 4]]
Second array
 [[5 6]
 [7 8]]
Result array
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [4]:
#using axis
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.concatenate((a,b),axis=1)
print("First array\n",a)
print("Second array\n",b)
print("Result array\n",c)

First array
 [[1 2]
 [3 4]]
Second array
 [[5 6]
 [7 8]]
Result array
 [[1 2 5 6]
 [3 4 7 8]]


In [10]:
#Joining arrays using stack function
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.stack((a,b),axis=1)
print(c)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [66]:
#stacking along rows
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.hstack((a,b))
print(c)
c=np.vstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]
[[1 2 3 4]
 [5 6 7 8]]


In [12]:
#Stacking along depth
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
c=np.dstack((a,b))
print(c)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [69]:
#Spliting arrays
import numpy as np
a=np.array([1,2,3,4,5,6])
b=np.array_split(a,2)
print(b)

[array([1, 2, 3]), array([4, 5, 6])]


In [70]:
#searching arrays using where()
#stores the index of element 4
import numpy as np
a=np.array([1,2,3,4,5,6,4,7,8,4])
b=np.where(a==4)
print(b)

(array([3, 6, 9], dtype=int64),)


In [71]:
#find the index of even elements using where()
import numpy as np
a=np.array([1,2,3,4,5,6,4,7,8,4])
b=np.where(a%2==0)
print(b)

(array([1, 3, 5, 6, 8, 9], dtype=int64),)


In [72]:
#Search sorted - consider the sorting of 'a' then assume adding element 7 to 'a' and return the position where it would be inserted
import numpy as np
a=np.array([10,2,3,9,0,1,8,4])
b=np.searchsorted(a,7)#2nd argument shows that where 7 should be inserted
print(b)
print(a)

6
[10  2  3  9  0  1  8  4]


In [76]:
#Search sorted - doing the same but finds the position from the right side
import numpy as np
a=np.array([10,2,3,9,0,1,8,4]) # 0 1 2 3 4 8 9 10
b=np.searchsorted(a,1,side='right')#2nd argument shows that where 7 should be inserted 
#if side='right' is removed then the position is 5
print(b)
print(a)

6
[10  2  3  9  0  1  8  4]
